server:
  port: ${WORKER_PORT:8081}

spring:
  application:
    name: grading-worker
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: ${RABBITMQ_PEFETCH:1}

judge:
  docker:
    cleanup-timeout: ${DOCKER_TIMEOUT:5s}

logging:
  level:
    com.solvemeup.worker: INFO
    com.github.dockerjava: WARN

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
