package com.solvemeup.smuworkerapi.worker.enums;

public enum ValueType {
    INT, LONG, BOOLEAN, CHAR, DOUBLE, STRING,
    INT_ARRAY, LONG_ARRAY, BOOLEAN_ARRAY, CHAR_ARRAY, DOUBLE_ARRAY, STRING_ARRAY,
    INT_2D_ARRAY, LONG_2D_ARRAY, BOOLEAN_2D_ARRAY, CHAR_2D_ARRAY, DOUBLE_2D_ARRAY, STRING_2D_ARRAY,
    INT_3D_ARRAY, LONG_3D_ARRAY, BOOLEAN_3D_ARRAY, CHAR_3D_ARRAY, DOUBLE_3D_ARRAY, STRING_3D_ARRAY
}
